fyb_backend_store_index:
    path: /
    methods: [GET]
    defaults:
        _controller: fyb.controller.store:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Store:index.html.twig
            sortable: true
            sorting:
                name: desc

fyb_backend_store_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: fyb.controller.store:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Store:create.html.twig
            redirect: fyb_backend_store_show

fyb_backend_store_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: fyb.controller.store:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Store:update.html.twig
            redirect: fyb_backend_store_show

fyb_backend_store_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: fyb.controller.store:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: fyb_backend_store_index

fyb_backend_store_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: fyb.controller.store:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Store:show.html.twig
            repository:
                method: findForDetailsPage
                arguments: [$id]
