Fyb\Component\Attribute\Model\Attribute:
    type: entity
    table: sylius_product_attribute
    fields:
        requirement:
            type: string
            length: 32
        filter:
            type: string
            length: 32
        backendWidget:
            column: backend_widget
            type: string
            length: 32
        frontendWidget:
            column: frontend_widget
            type: string
            length: 32
    oneToMany:
        widgets:
            targetEntity: Fyb\Component\Attribute\Model\AttributeWidget
            mappedBy: attribute