sylius_resource:
    resources:
        fyb.attribte_widget:
            classes:
                model: Fyb\Component\Attribute\Model\AttributeWidget
                repository: Fyb\Bundle\AttributeBundle\Doctrine\ORM\AttributeWidgetRepository
        fyb.store:
            classes:
                model: Fyb\Component\Store\Model\Store
