sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: AppBundle\Entity\Attribute
                    form:
                      default: AppBundle\Form\Type\AttributeType
            attribute_value:
                classes:
                    model: AppBundle\Entity\AttributeValue