sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    controller: AppBundle\Controller\AttributeController
                    model: AppBundle\Entity\Attribute
                    form:
                      default: AppBundle\Form\Type\AttributeType
            attribute_value:
                classes:
                    model: AppBundle\Entity\AttributeValue
                    form:
                        default: AppBundle\Form\Type\AttributeValueType