sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    controller: AppBundle\Controller\AttributeController
                    model: AppBundle\Entity\Attribute
                    form:
                      default: AppBundle\Form\Type\AttributeType
            attribute_value:
                classes:
                    model: AppBundle\Entity\AttributeValue
                    form:
                        default: AppBundle\Form\Type\AttributeValueType
sylius_archetype:
    resources:
        product:
            archetype:
                classes:
                    model: AppBundle\Entity\Archetype
                    form:
                      default: AppBundle\Form\Type\ArchetypeType
sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: AppBundle\Entity\Taxon
                form:
                  default: AppBundle\Form\Type\TaxonType

sylius_product:
    resources:
        product:
            classes:
                model: AppBundle\Entity\Product
                form:
                    default: AppBundle\Form\Type\ProductType