sylius_backend_taxonomy_show:
    path: administration/taxonomies/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Taxonomy:show.html.twig
            sortable: true
            sorting:
                productArchetype: desc
                serviceArchetype: desc

sylius_backend_render_attribute_widget_forms:
    path: administration/product-attributes/attribute-widget-forms
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:renderAttributeWidgetFormsAction