sylius_backend_taxonomy_show:
    path: administration/taxonomies/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Taxonomy:show.html.twig
            sortable: true
            sorting:
                productArchetype: desc
                serviceArchetype: desc