AppBundle\Entity\Archetype:
    type: entity
    table: sylius_product_archetype
    fields:
        type:
            type: string
            length: 32
    oneToMany:
        widgets:
            targetEntity: AppBundle\Entity\AttributeWidget
            mappedBy: archetype