AppBundle\Entity\AttributeWidget:
    repositoryClass: AppBundle\Doctrine\ORM\WidgetRepository
    type: entity
    table: sylius_product_archetype_attribute_widget
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        backendWidget:
            column: backend_widget
            type: string
            length: 32
        frontendWidget:
            column: frontend_widget
            type: string
            length: 32

    manyToOne:
        archetype:
            targetEntity: AppBundle\Entity\Archetype
            inversedBy: widgets
            joinColumn:
                name: archetype_id
                referencedColumnName: id
        attribute:
            targetEntity: AppBundle\Entity\Attribute
            inversedBy: widgets
            joinColumn:
                name: attribute_id
                referencedColumnName: id