AppBundle\Entity\Taxon:
    type: entity
    table: sylius_taxon
    oneToOne:
        productArchetype:
            targetEntity: AppBundle\Entity\Archetype
            joinColun:
                name: product_archetype_id
                referencedColumnName: id
        serviceArchetype:
            targetEntity: AppBundle\Entity\Archetype
            joinColun:
                name: service_archetype_id
                referencedColumnName: id